version: '3.3'
services:
  db:
    image: mysql:latest
    # network_mode: bridge
    # restart: always
    environment:
      MYSQL_DATABASE: 'gain'
      # MYSQL_USER: 'pablo'
      # MYSQL_PASSWORD: 'Admin@123'
      MYSQL_ROOT_PASSWORD: 'Admin@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - ./data:/var/lib/mysql
# Names our volume
# volumes:
#   my-db:
    # driver: local